version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPO_URI=$(aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --query 'repositories[0].repositoryUri' --output text)
      - echo "Repository URI: $REPO_URI"
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $REPO_URI:latest
  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push $REPO_URI:latest
      - echo "Creating imagedefinitions.json for ECS deployment"
      - echo '[{"name":"backend","imageUri":"'$REPO_URI':latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
