version: 0.2
phases:
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:latest .
      - $(aws ecr get-login --no-include-email)
      - docker tag $IMAGE_REPO_NAME:latest $IMAGE_URI
      - docker push $IMAGE_URI
